const BOOKING_URL='https://secuream.e-gds.com/mamacucharabyarthotels/shoppingcart/availability.aspx?hotelid=461';
const IMG={
  house:'https://hotelotavalo.com/wp-content/uploads/2026/05/slider-1.jpg',
  roomLuxury:'https://hotelotavalo.com/wp-content/uploads/revslider/o/9/1679ec66b0d273e25c0eca01c4bf8432.webp',
  roomTub:'https://hotelotavalo.com/wp-content/uploads/revslider/o/9/b168ee34804b96fb02a7d364facba6a4.webp',
  roomDeluxe:'https://hotelotavalo.com/wp-content/uploads/revslider/o/9/fa646ab66294c9684f7573e8aab89dd6.webp',
  roomInterior:'https://hotelotavalo.com/wp-content/uploads/revslider/o/9/28176bc0cab1af1b6a991782d8427b02.webp',
  premium:'https://hotelotavalo.com/wp-content/uploads/2026/05/premium-3.jpg',
  luxury1:'https://hotelotavalo.com/wp-content/uploads/2026/05/luxury-1.jpg',
  luxury2:'https://hotelotavalo.com/wp-content/uploads/2026/05/luxury-2.jpg',
  luxury3:'https://hotelotavalo.com/wp-content/uploads/2026/05/luxury-3.jpg',
  deluxe1:'https://hotelotavalo.com/wp-content/uploads/2026/05/deluxe-1.jpg',
  deluxe2:'https://hotelotavalo.com/wp-content/uploads/2026/05/deluxe-2.jpg',
  deluxe3:'https://hotelotavalo.com/wp-content/uploads/2026/05/deluxe-3.jpg',
  superior1:'https://hotelotavalo.com/wp-content/uploads/2026/05/superior-1.jpg',
  superior2:'https://hotelotavalo.com/wp-content/uploads/2026/05/superior-2.jpg',
  superior3:'https://hotelotavalo.com/wp-content/uploads/2026/05/superior-3.jpg',
  premium1:'https://hotelotavalo.com/wp-content/uploads/2026/05/premium-1.jpg',
  premium2:'https://hotelotavalo.com/wp-content/uploads/2026/05/premium-2.jpg',
  premium3:'https://hotelotavalo.com/wp-content/uploads/2026/05/premium-3.jpg',
  sarance:'https://hotelotavalo.com/wp-content/uploads/2026/05/sarance-8.jpg',
  rooftop:'https://hotelotavalo.com/wp-content/uploads/2026/05/nukanchikwan-7.jpg',
  equator:'https://hotelotavalo.com/wp-content/uploads/2026/05/equator-face-5.jpg',
  equator1:'https://hotelotavalo.com/wp-content/uploads/2026/05/equator-face-1.jpg',
  equator2:'https://hotelotavalo.com/wp-content/uploads/2026/05/equator-face-2.jpg',
  equator3:'https://hotelotavalo.com/wp-content/uploads/2026/05/equator-face-3.jpg',
  equator4:'https://hotelotavalo.com/wp-content/uploads/2026/05/equator-face-4.jpg',
  kawsaymi:'https://hotelotavalo.com/wp-content/uploads/2026/05/kawsaymi-5.jpg',
  kawsaymi1:'https://hotelotavalo.com/wp-content/uploads/2026/05/kawsaymi-1.jpg',
  kawsaymi2:'https://hotelotavalo.com/wp-content/uploads/2026/05/kawsaymi-2.jpg',
  kawsaymi3:'https://hotelotavalo.com/wp-content/uploads/2026/05/kawsaymi-3.jpg',
  kawsaymi4:'https://hotelotavalo.com/wp-content/uploads/2026/05/kawsaymi-4.jpg',
  taita:'https://hotelotavalo.com/wp-content/uploads/2026/05/taita-gundo-1.jpg',
  taita2:'https://hotelotavalo.com/wp-content/uploads/2026/05/taita-gundo-2.jpg',
  taita3:'https://hotelotavalo.com/wp-content/uploads/2026/05/taita-gundo-3.jpg',
  taita4:'https://hotelotavalo.com/wp-content/uploads/2026/05/taita-gundo-4.jpg',
  taita5:'https://hotelotavalo.com/wp-content/uploads/2026/05/taita-gundo-5.jpg',
  sombreros:'https://hotelotavalo.com/wp-content/uploads/2026/05/sombreros-iluman-5.jpg',
  sombreros1:'https://hotelotavalo.com/wp-content/uploads/2026/05/sombreros-iluman-1.jpg',
  sombreros2:'https://hotelotavalo.com/wp-content/uploads/2026/05/sombreros-iluman-2.jpg',
  sombreros3:'https://hotelotavalo.com/wp-content/uploads/2026/05/sombreros-iluman-3.jpg',
  sombreros4:'https://hotelotavalo.com/wp-content/uploads/2026/05/sombreros-iluman-4.jpg',
  nayia:'https://hotelotavalo.com/wp-content/uploads/2026/05/arte-nayia-1.jpg',
  nayia2:'https://hotelotavalo.com/wp-content/uploads/2026/05/arte-nayia-2.jpg',
  nayia3:'https://hotelotavalo.com/wp-content/uploads/2026/05/arte-nayia-3.jpg'
};
const HOTEL_CONTACT={phone:'+593 (6) 292-8710',frontDesk:'+593 (99) 341-2224',email:'otavalo@arthotelsecuador.com',info:'info@arthotelsecuador.com',address:'C. Vicente Ramón Roca 504, Otavalo'};
const common={es:{nav:['Hotel','Habitaciones','Experiencias','Gastronomía','Otavalo'],reserve:'Reservar',back:'Volver al inicio',discover:'También puedes descubrir',book:'Consultar disponibilidad',footer:'Concepto de rediseño · 2026'},en:{nav:['Hotel','Rooms','Experiences','Gastronomy','Otavalo'],reserve:'Book',back:'Back to home',discover:'You may also discover',book:'Check availability',footer:'Redesign concept · 2026'}};
