(() => {
  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const gsap = window.gsap;
  const ScrollTrigger = window.ScrollTrigger;
  const SplitText = window.SplitText;

  const setActiveScene = (steps, frames, index, current) => { steps.forEach((s,i)=>s.classList.toggle('is-active',i===index)); frames.forEach((f,i)=>f.classList.toggle('is-active',i===index)); if(current) current.textContent=String(index+1).padStart(2,'0'); };
  const observerScene=(stepSelector,frameSelector,currentSelector)=>{const steps=[...document.querySelectorAll(stepSelector)],frames=[...document.querySelectorAll(frameSelector)],current=document.querySelector(currentSelector);if(!steps.length||!frames.length)return;setActiveScene(steps,frames,0,current);const o=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveScene(steps,frames,Number(visible.target.dataset.sceneIndex||0),current)},{threshold:[.35,.55,.72],rootMargin:'-18% 0px -30% 0px'});steps.forEach(s=>o.observe(s));};

  const tasteButtons=[...document.querySelectorAll('[data-taste-trigger]')],tastePanels=[...document.querySelectorAll('[data-taste-panel]')];let tasteIndex=0,tasteTimer;
  const setTaste=name=>{tasteIndex=Math.max(0,tasteButtons.findIndex(b=>b.dataset.tasteTrigger===name));tasteButtons.forEach(b=>{const a=b.dataset.tasteTrigger===name;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',String(a))});tastePanels.forEach(p=>p.classList.toggle('is-active',p.dataset.tastePanel===name));};
  const startTasteAuto=()=>{clearInterval(tasteTimer);if(reduceMotion||tasteButtons.length<2)return;tasteTimer=setInterval(()=>{tasteIndex=(tasteIndex+1)%tasteButtons.length;setTaste(tasteButtons[tasteIndex].dataset.tasteTrigger)},4800)};
  tasteButtons.forEach(b=>b.addEventListener('click',()=>{setTaste(b.dataset.tasteTrigger);startTasteAuto()}));if(tasteButtons.length){setTaste(tasteButtons[0].dataset.tasteTrigger);startTasteAuto();}

  const cookieCard=document.getElementById('v3Cookies'),cookieChoice=localStorage.getItem('hotelOtavaloCookies');if(cookieCard&&!cookieChoice)setTimeout(()=>{cookieCard.classList.add('is-visible');if(gsap&&!reduceMotion)gsap.to(cookieCard,{opacity:1,y:0,duration:.6,ease:'power3.out'});else{cookieCard.style.opacity='1';cookieCard.style.transform='none'}},2200);document.querySelectorAll('[data-cookie-choice]').forEach(btn=>btn.addEventListener('click',()=>{localStorage.setItem('hotelOtavaloCookies',btn.dataset.cookieChoice);if(gsap&&!reduceMotion)gsap.to(cookieCard,{opacity:0,y:12,duration:.35,ease:'power2.in',onComplete:()=>cookieCard?.remove()});else cookieCard?.remove()}));

  if(!gsap||!ScrollTrigger||reduceMotion){document.getElementById('v3Intro')?.remove();document.querySelectorAll('.v3-reveal-media').forEach(el=>el.style.clipPath='none');observerScene('[data-heritage-step]','[data-heritage-frame]','#heritageProgress');return;}
  gsap.registerPlugin(ScrollTrigger);if(SplitText)gsap.registerPlugin(SplitText);
  if(window.Lenis){const lenis=new window.Lenis({duration:1.06,smoothWheel:true,wheelMultiplier:.92,touchMultiplier:1.1});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(time=>lenis.raf(time*1000));gsap.ticker.lagSmoothing(0);window.hotelOtavaloLenis=lenis;}

  const intro=document.getElementById('v3Intro'),introProgress=intro?.querySelector('.v3-intro-progress i'),introArch=intro?.querySelector('.v3-intro-arch'),introCopy=intro?.querySelectorAll('.v3-intro-copy > *'),hero=document.querySelector('.hero-v2'),heroMedia=hero?.querySelector('.hero-media'),heroKicker=hero?.querySelector('.hero-kicker'),heroCopy=hero?.querySelector('.hero-copy'),heroActions=hero?.querySelector('.hero-actions'),heroFoot=hero?.querySelector('.hero-foot'),hero360=hero?.querySelector('.hero-360'),award=document.getElementById('v3Award');
  let titleSplit=null;const heroTitle=document.getElementById('hero-title');if(SplitText&&heroTitle)titleSplit=new SplitText(heroTitle,{type:'lines',linesClass:'v3-title-line'});
  const entrance=gsap.timeline({defaults:{ease:'power3.out'}});if(intro){entrance.set(intro,{yPercent:0}).fromTo(introCopy,{y:18,opacity:0},{y:0,opacity:1,duration:.65,stagger:.08}).to(introProgress,{scaleX:1,duration:.8,ease:'power2.inOut'},'<.05').to(introArch,{scale:1.045,duration:.75,ease:'power2.inOut'},'<.15').to(intro,{yPercent:-100,duration:.9,ease:'power4.inOut'}).set(intro,{display:'none'}).add(()=>intro.classList.add('is-gone'));}
  if(heroMedia)entrance.fromTo(heroMedia,{clipPath:'inset(12% 10% 12% 10%)',scale:1.08},{clipPath:'inset(0)',scale:1.025,duration:1.05,ease:'power4.out'},intro?'-=.52':0);if(heroKicker)entrance.from(heroKicker,{y:16,opacity:0,duration:.5},'-=.68');if(titleSplit?.lines?.length)entrance.from(titleSplit.lines,{yPercent:112,opacity:0,duration:.82,stagger:.08,ease:'power4.out'},'-=.44');else if(heroTitle)entrance.from(heroTitle,{y:34,opacity:0,duration:.82},'-=.44');entrance.from([heroCopy,heroActions].filter(Boolean),{y:18,opacity:0,duration:.58,stagger:.08},'-=.42');if(heroFoot)entrance.from(heroFoot.children,{y:14,opacity:0,duration:.5,stagger:.06},'-=.3');if(hero360)entrance.from(hero360,{scale:.74,opacity:0,rotate:8,duration:.72,ease:'back.out(1.3)'},'-=.36');if(award)entrance.fromTo(award,{scale:.62,rotate:-9,opacity:0},{scale:1,rotate:0,opacity:1,duration:.78,ease:'back.out(1.45)'},'-=.44');
  if(hero&&award){const hide=()=>gsap.to(award,{y:-30,scale:.72,rotate:5,opacity:0,duration:.44,ease:'power3.inOut',overwrite:true}),show=()=>gsap.to(award,{y:0,scale:1,rotate:0,opacity:1,duration:.58,ease:'back.out(1.25)',overwrite:true});ScrollTrigger.create({trigger:hero,start:'top+=100 top',end:'bottom top',onEnter:hide,onLeaveBack:show});}if(hero&&heroMedia)gsap.to(heroMedia,{yPercent:7,ease:'none',scrollTrigger:{trigger:hero,start:'top top',end:'bottom top',scrub:true}});

  const heritageSteps=[...document.querySelectorAll('[data-heritage-step]')],heritageFrames=[...document.querySelectorAll('[data-heritage-frame]')],heritageCurrent=document.querySelector('#heritageProgress');const activateHeritage=index=>{heritageSteps.forEach((s,i)=>s.classList.toggle('is-active',i===index));heritageFrames.forEach((f,i)=>{const active=i===index;f.classList.toggle('is-active',active);gsap.to(f,{opacity:active?1:0,scale:active?1:1.025,duration:.68,ease:'power3.out',overwrite:true})});if(heritageCurrent)heritageCurrent.textContent=String(index+1).padStart(2,'0')};if(heritageSteps.length&&heritageFrames.length){activateHeritage(0);heritageSteps.forEach((s,i)=>ScrollTrigger.create({trigger:s,start:'top 56%',end:'bottom 44%',onEnter:()=>activateHeritage(i),onEnterBack:()=>activateHeritage(i)}));}document.querySelectorAll('[data-heritage-step] .year').forEach(year=>gsap.from(year,{xPercent:-10,opacity:.18,ease:'none',scrollTrigger:{trigger:year,start:'top 82%',end:'center 54%',scrub:true}}));

  const stayArea=document.querySelector('.stay-horizontal'),stayTrack=document.querySelector('.stay-horizontal-track'),stayProgress=document.querySelector('.stay-horizontal-progress');
  if(stayArea&&stayTrack&&matchMedia('(min-width:761px)').matches){
    gsap.fromTo(stayArea,{scale:.92,opacity:.82},{scale:1,opacity:1,ease:'none',scrollTrigger:{trigger:stayArea,start:'top 82%',end:'top 24%',scrub:true}});
    const distance=()=>Math.max(0,stayTrack.scrollWidth-stayArea.clientWidth);
    const roomScroll=gsap.to(stayTrack,{x:()=>-distance(),ease:'none',scrollTrigger:{trigger:stayArea,start:'top 18%',end:()=>`+=${Math.max(distance(),innerWidth*1.25)}`,scrub:.85,pin:true,anticipatePin:1,invalidateOnRefresh:true,onUpdate:self=>stayProgress?.style.setProperty('--stay-progress',String(Math.max(.06,self.progress)))}});
    document.querySelectorAll('.stay-card').forEach((card,i)=>{const img=card.querySelector('img');if(img)gsap.fromTo(img,{xPercent:i%2?4:-4,scale:1.065},{xPercent:i%2?-3:3,scale:1.01,ease:'none',scrollTrigger:{trigger:stayArea,start:'top 18%',end:()=>`+=${Math.max(distance(),innerWidth*1.25)}`,scrub:true}})});
    let dragging=false,startX=0,startY=0,moved=false;stayArea.style.cursor='grab';
    stayArea.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;moved=false;startX=e.clientX;startY=scrollY;stayArea.setPointerCapture?.(e.pointerId);stayArea.style.cursor='grabbing';document.body.classList.add('room-dragging')});
    stayArea.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX;if(Math.abs(dx)>5)moved=true;scrollTo({top:startY-dx*2.1,behavior:'auto'});e.preventDefault()});
    const stopDrag=e=>{if(!dragging)return;dragging=false;stayArea.releasePointerCapture?.(e.pointerId);stayArea.style.cursor='grab';document.body.classList.remove('room-dragging');if(moved){const blocker=ev=>{ev.preventDefault();ev.stopPropagation();stayArea.removeEventListener('click',blocker,true)};stayArea.addEventListener('click',blocker,true)}};
    stayArea.addEventListener('pointerup',stopDrag);stayArea.addEventListener('pointercancel',stopDrag);window.addEventListener('resize',()=>roomScroll.scrollTrigger?.refresh(),{passive:true});
  }

  const experienceScene=document.querySelector('.experience-scene'),experienceTiles=[...document.querySelectorAll('.experience-tile')],trajectories=[{x:-36,y:90,rotate:-2.2},{x:44,y:52,rotate:2.1},{x:-18,y:120,rotate:1.3},{x:46,y:94,rotate:-1.5},{x:-42,y:64,rotate:2.4}];experienceTiles.forEach((tile,i)=>{const t=trajectories[i]||trajectories[0];gsap.from(tile,{x:t.x,y:t.y,rotate:t.rotate,opacity:0,duration:1.05,ease:'power4.out',scrollTrigger:{trigger:experienceScene||tile,start:'top 76%',toggleActions:'play none none reverse'},delay:i*.06});const img=tile.querySelector('img');if(img)gsap.fromTo(img,{yPercent:-8,scale:1.07},{yPercent:5,scale:1.015,ease:'none',scrollTrigger:{trigger:experienceScene||tile,start:'top bottom',end:'bottom top',scrub:true}})});const centerMark=document.querySelector('.experience-center-mark');if(centerMark&&experienceScene)gsap.fromTo(centerMark,{scale:.86,opacity:.25},{scale:1.04,opacity:1,ease:'none',scrollTrigger:{trigger:experienceScene,start:'top 70%',end:'bottom 35%',scrub:true}});
  const thread=document.querySelector('.experience-thread');if(thread){thread.querySelectorAll('path').forEach((path,i)=>{const length=path.getTotalLength?.()||1000;gsap.set(path,{strokeDasharray:`${length*.05} ${length*.035}`,strokeDashoffset:length*.22});gsap.to(path,{strokeDashoffset:-length*.26,ease:'none',scrollTrigger:{trigger:'.experience-scene',start:'top bottom',end:'bottom top',scrub:true},delay:i*.06})});gsap.to(thread,{yPercent:16,rotate:4,ease:'none',scrollTrigger:{trigger:'.experience-scene',start:'top bottom',end:'bottom top',scrub:true}})}
  document.querySelectorAll('.v3-reveal-media').forEach(media=>gsap.to(media,{clipPath:'inset(0)',duration:1.05,ease:'power4.out',scrollTrigger:{trigger:media,start:'top 82%',once:true}}));document.querySelectorAll('.v3-split').forEach(node=>{if(!SplitText)return;const split=new SplitText(node,{type:'lines',linesClass:'v3-copy-line'});gsap.from(split.lines,{yPercent:110,opacity:0,duration:.8,stagger:.07,ease:'power4.out',scrollTrigger:{trigger:node,start:'top 82%',once:true}})});document.querySelectorAll('.v3-magnetic').forEach(el=>{const xTo=gsap.quickTo(el,'x',{duration:.45,ease:'power3.out'}),yTo=gsap.quickTo(el,'y',{duration:.45,ease:'power3.out'});el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();xTo((e.clientX-(r.left+r.width/2))*.12);yTo((e.clientY-(r.top+r.height/2))*.12)});el.addEventListener('pointerleave',()=>{xTo(0);yTo(0)})});document.querySelectorAll('.journey-card').forEach(card=>{const img=card.querySelector('img');if(img)gsap.fromTo(img,{yPercent:-4},{yPercent:4,ease:'none',scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:true}})});ScrollTrigger.refresh();
})();